# Generated by Django 3.2.3 on 2021-07-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                #('passwd', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('cont', models.TextField()),
                ('bdate', models.DateTimeField()),
                ('readcnt', models.IntegerField()),
                ('gnum', models.IntegerField()),
                ('onum', models.IntegerField()),
                ('nested', models.IntegerField()),
                ('type', models.CharField(max_length=10)),
            ],
        ),
    ]
