# Generated by Django 3.2.3 on 2021-07-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarinfoComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carid', models.IntegerField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=100, null=True)),
                ('rdate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'carinfo_comments',
                'managed': False,
            },
        ),
    ]
